### PR TITLE
update pkg for twistlock

### PR DESCRIPTION
**Pull request by bluzarraga**
Same problem as in NSS, there was a huge jump from 1.2.1 to 1.11.1 which changed a whole lot of other packages. Probably best to confirm this works as expected before merging.

### CODE REVIEW

**Comment by bluzarraga** [comment]
not sure why this is failing, after updating the package go-logr, the build completed and I was able to deploy the image and successfully test against the SERT regression tests. This pr should be good to go and it seems like the problem here is the exact same as the one in namespacescope

**Comment by bluzarraga** [comment]
going to take the same approach as I did in https://github.com/IBM/ibm-namespace-scope-operator/pull/221

**Comment by bluzarraga** [comment]
check passed here as well, will build and test locally

**Comment by bluzarraga** [comment]
All checks passed, regression test passed as well. This PR is good to go.

**Review by Daniel-Fan — APPROVED** [review]
/lgtm

**Pull request merged**
